Header hero branch
ITeam-by-GOIT/ice-cream pull request #12
Opened 2021-03-12 21:08 UTC by ikalyniak

могут быть конфликты с свг и тайтлами

2021-03-12 22:52 UTC, Koliadjun requested changes
Поправ невеликі помилки. Ну і хотів би обговорити ЛОГО.

2021-03-12 22:52 UTC, ghost commented on src/partials/header-hero.html
> +    <button class="btn-toggle" id="menu-toggle" data-menu-button>
http://joxi.ru/brRWvMjfObV40m
валідатор матюкається.
Error: Element div not allowed as child of element button in this context. (Suppressing further errors from this subtree.)

Може можна span?

2021-03-12 22:52 UTC, Koliadjun commented on src/sass/layout/_header-hero.scss
> +    margin-right: 110px;
http://joxi.ru/nAy4RZQiwnG3a2
постав цей марджн у силку

2021-03-12 22:52 UTC, Koliadjun commented on src/partials/header-hero.html
> +      <a class="header-logo link" href="./index.html">
Якось дуже складно зроблено. може так
```
<a href="" class="logo">
  Icecream
  <span>
    <svg>
      <use></use>
    </svg>
  </span>
</a>
```
span абсолютом?

2021-03-12 22:52 UTC, Koliadjun commented on src/partials/header-hero.html
> +    <button class="header-button btn-light" type="button">
тут можна без span?! Але якщо його треба то відпиши тут для чого.

2021-03-12 22:59 UTC, ikalyniak commented on src/partials/header-hero.html
> +      <a class="header-logo link" href="./index.html">
нет) если откроешь стили, то будет видно, что
-header-logo__box = релатив, относительно которого позиционируется лого, это должен быть родитель;
-header-logo__icon-box =контейнер, чтобы поставить иконку по центру 
-header-logo__caption =для стилизации текста лого

2021-03-12 23:05 UTC, ikalyniak commented on src/partials/header-hero.html
> +    <button class="header-button btn-light" type="button">
нужен для маржина, чтобы  оттолкнуть свг, смотри сразу со стилями-тогда сразу ясно

2021-03-12 23:12 UTC, ikalyniak commented on src/sass/layout/_header-hero.scss
> +    margin-right: 110px;
согласен, исправил

2021-03-12 23:18 UTC, ikalyniak commented on src/partials/header-hero.html
> +    <button class="btn-toggle" id="menu-toggle" data-menu-button>
отлично! принимается, исправил

2021-03-12 23:34 UTC, ikalyniak commented
> Поправ невеликі помилки. Ну і хотів би обговорити ЛОГО.

div/span в бургере + margin на ссылку-лого исправил, остальные замечания прокомментировал

2021-03-13 00:35 UTC, Koliadjun commented on src/partials/header-hero.html
> +      <a class="header-logo link" href="./index.html">
`-header-logo__box ` забрати, а релатив   зробити `<a class="header-logo link" href="./index.html">`
`header-logo__icon-box` зробити span 
`header-logo__icon-box` написати стилі в  `header-logo` і видалити span

2021-03-13 00:36 UTC, Koliadjun commented on src/partials/header-hero.html
> +    <button class="header-button btn-light" type="button">
можна SVG дати margin-left. Чи ні?

2021-03-13 00:41 UTC, Koliadjun commented on src/partials/header-hero.html
> +      <a class="header-logo link" href="./index.html">
І щоб не вибивати тільки іконку в абсолют, як варіант можна все лого абсолютом змістити або попробувати `transform: translateX()` і тоді не буде розриву не клікабельного між лого і іконкою. То тільки пропозиція.

2021-03-13 00:49 UTC, ikalyniak commented on src/partials/header-hero.html
> +      <a class="header-logo link" href="./index.html">
1.я не уверен, что с помощью <а> можно ловить абсолюты, может ошибаюсь, но вроде Репин что-тот об этом говорил. Нужно уточнить у Дениса
2. зачем делать слан, если сейчас стоит див? чем слан лучше дива? и то, и то обертка...
3. вообще непонятно, что ты имеешь ввиду, спан нужен чтобы на планшете толкать марджином свг

2021-03-13 00:51 UTC, ikalyniak commented on src/partials/header-hero.html
> +    <button class="header-button btn-light" type="button">
Марджины работают только с блоками, как ты хочешь толкать текст?

2021-03-13 17:44 UTC, Koliadjun approved these changes
Класна кнопка для бургера. Все ок

2021-03-13 17:44 UTC, merged