Contacts
ITeam-by-GOIT/ice-cream pull request #8
Opened 2021-03-12 11:03 UTC by bogdankol

там файл спрайта - он не должен конфликтовать, взял я его с ветки dev, но добавил свою иконку правой стрелочки (она отличается от просто правой стрелочки, которую заспрайтила Оля)....добавил цвет текста, жирность и тень

2021-03-12 12:18 UTC, bogdankol commented
че то какая-то фигня с иконкой - не меняется цвет, попробую исправить

2021-03-12 14:32 UTC, Koliadjun requested changes
Виправ дані зауваження.

2021-03-12 14:32 UTC, ghost commented on src/sass/main.scss
> +@import './layout/contacts';
В layout/_main.scss є підключений contacts.scss

2021-03-12 14:32 UTC, ghost commented on src/sass/utils/_variables.scss
> +  // contacts
Порожній коментар. Потрібно видалити

2021-03-12 14:32 UTC, ghost commented on src/sass/base/_common.scss
> +ul {
Ми вже домовились використовувати клас. Така зміна поламає іншим верстку. Поміняй на клас .list і додай клас до своїх ul

2021-03-12 14:32 UTC, ghost commented on src/partials/contacts.html
> +                <button type="button" class="contacts__button">Our Locations
в нас є універсальний клас для кнопок в components/_button.scss

2021-03-12 14:32 UTC, ghost commented on src/partials/contacts.html
> +                <button type="button" class="contacts__button">Franchise
в нас є універсальний клас для кнопок в components/_button.scss

2021-03-12 14:32 UTC, ghost commented on src/sass/layout/_contacts.scss
> +.container {
Даний клас описаний. Якщо це для тесту то в DEV не заливай

2021-03-12 14:32 UTC, ghost commented on src/sass/layout/_contacts.scss
> +.contacts__item-header {
Те, що не використовуєш закоментуй (потім може знадобитись)

2021-03-12 14:34 UTC, AngieBoiko reviewed
поправки по ветке contacts

2021-03-12 14:34 UTC, AngieBoiko commented on src/sass/base/_common.scss
> +ul {
вчера на миттинге договорились оставить класс .list, базовые найстройки не надо самостоятельно менять, только добавляем переменные, после fatch origin и проверки нет ли уже таких

2021-03-12 14:34 UTC, AngieBoiko commented on src/sass/main.scss
> +@import './layout/contacts';
паршал _contacts.scss  уже подключен @import './layout/main';

2021-03-12 14:34 UTC, AngieBoiko commented on src/sass/layout/_contacts.scss
> +.container {
у нас уже есть .container, класс закреплен src/sass/base/_container.scss

2021-03-12 14:36 UTC, AngieBoiko commented on src/sass/base/_common.scss
> +ul {
@Koliadjun  мы одновременно смотрели код))) написала тоже комментарии по этому поводу)

2021-03-12 14:37 UTC, Koliadjun commented
![](https://github.trello.services/images/mini-trello-icon.png) [contacts](https://trello.com/c/ol3UP58V/49-contacts)

2021-03-12 21:53 UTC, ikalyniak commented on src/images/contacts_background/section_dots.svg
> +<image id="image0" width="1920" height="382" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB4AAAAF+CAMAAABUNPenAAAAeFBMVEUAAAD/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/
что это ?

2021-03-12 21:57 UTC, ikalyniak commented on src/partials/contacts.html
> +                    <li class="item item--black">Chicago</li>
модификатор не может существовать без самого элемента. 
contacts =это блок
contacts__item =это элемент блока
contacts__item--black =это модификатор элемента

2021-03-12 22:18 UTC, ikalyniak commented on src/partials/contacts.html
> +                <button type="button" class="contacts__button">Franchise
универсальный класс как раз и задает правильный фон и цвет, а не просто красный. А паддинги, высота и жирность текста на  секции контактов и в герое  разные поэтому их нужно прописывать самому

2021-03-12 22:20 UTC, ikalyniak commented on src/sass/layout/_contacts.scss
> +  }
мы же вроде используем компоненты, контейнер есть в base

2021-03-13 14:52 UTC, bogdankol commented
вроде все исправил

2021-03-13 17:55 UTC, bogdankol commented on src/sass/main.scss
> +@import './layout/contacts';
+

2021-03-13 17:55 UTC, bogdankol commented on src/sass/utils/_variables.scss
> +  // contacts
+

2021-03-13 17:56 UTC, bogdankol commented on src/sass/utils/_variables.scss
> +  // contacts
=

2021-03-13 17:56 UTC, bogdankol commented on src/sass/utils/_variables.scss
> +  // contacts
+++

2021-03-14 12:40 UTC, bogdankol commented on src/sass/base/_common.scss
> +ul {
+++

2021-03-14 12:40 UTC, bogdankol commented on src/partials/contacts.html
> +                <button type="button" class="contacts__button">Franchise
+++

2021-03-14 12:40 UTC, bogdankol commented on src/sass/layout/_contacts.scss
> +.container {
+++

2021-03-14 12:41 UTC, bogdankol commented on src/sass/layout/_contacts.scss
> +.contacts__item-header {
+++

2021-03-14 12:41 UTC, bogdankol commented on src/images/contacts_background/section_dots.svg
> +<image id="image0" width="1920" height="382" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB4AAAAF+CAMAAABUNPenAAAAeFBMVEUAAAD/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/uMn/
+++

2021-03-14 12:41 UTC, bogdankol commented
вроде все сделал, остались модалки

2021-03-14 14:25 UTC, AngieBoiko commented on src/sass/layout/_contacts.scss
> +  background: #f0d1a5;
давай я сделаю переменную для этого цвета, он у менят в секции тоже есть, назову --bg-beige-color. Можешь себе ее ставить сразу, при фетче подтянится

2021-03-14 14:25 UTC, AngieBoiko commented on src/sass/utils/_variables.scss
> +  --color-even-contacts: #C2E297;
этот цвет повторяется у меня в секции, давай его назовем универсально --bg-green-color, я сейчас у себя довалю в переменные и будем уже сливать ветку, удали пожалуйста у себя из переменны,  в стилях поменяй на новое название, при фетче должно подтянутся без конфликтов

2021-03-14 21:45 UTC, bogdankol commented on src/sass/layout/_contacts.scss
> +  background: #f0d1a5;
окей, добавил var

2021-03-14 21:55 UTC, bogdankol commented on src/sass/utils/_variables.scss
> +  --color-even-contacts: #C2E297;
окей, удалил и поменял

2021-03-14 21:56 UTC, bogdankol commented on src/sass/utils/_variables.scss
> +  --color-even-contacts: #C2E297;
пушу

2021-03-14 22:33 UTC, Koliadjun approved these changes

2021-03-14 22:34 UTC, merged