About
ITeam-by-GOIT/ice-cream pull request #9
Opened 2021-03-12 15:50 UTC by funnykoss

разметка и соновные стили сделала,фотографии подставила разных размеров,есть еще небольшие недочеты,но данный этап хотелось бы смерджить, чтобы можно было приступить к следующей ветке

2021-03-12 19:44 UTC, AngieBoiko commented on src/partials/about.html
> +        <p class="section_subtitle">tradition and love</p>
можно поменять на section-subtitle section-title, как договорились на миттинге)

2021-03-12 19:48 UTC, ikalyniak approved these changes

2021-03-12 19:54 UTC, Koliadjun commented
![](https://github.trello.services/images/mini-trello-icon.png) [about](https://trello.com/c/w8txdhVL/46-about)

2021-03-12 20:26 UTC, funnykoss commented on src/partials/about.html
> +        <p class="section_subtitle">tradition and love</p>
исправила

2021-03-12 20:27 UTC, funnykoss commented
исправила)жду мерджа,чтобы творить или вытворять дальше)

2021-03-12 20:34 UTC, Koliadjun requested changes
В загальному переглянь чи добрий в тебе макет бо я дивився по Денисовому. Є різниця марджинів і падінгів. І поміняй падінги на марджини. Блоки між собою відштовхуються марджинами

2021-03-12 20:34 UTC, ghost commented on src/sass/layout/_about.scss
> +  margin-top: 17px;
http://joxi.ru/V2VZjlpCknGwj2

2021-03-12 20:34 UTC, ghost commented on src/sass/layout/_about.scss
> +  margin-bottom: 49px;
http://joxi.ru/l2ZOpdMI7nV6RA

2021-03-12 20:34 UTC, ghost commented on src/sass/layout/_about.scss
> +  width: 220px;
http://joxi.ru/krDXw34t4nd1pr 
Можливо нехай тягнеться по ширини? Як команда вважає?

2021-03-12 20:34 UTC, ghost commented on src/sass/layout/_about.scss
> +  padding-top: 134px;
http://joxi.ru/Q2KNvy4Tv8gnjm
Перевір чи в тебе макет не поплив

2021-03-12 20:34 UTC, ghost commented on src/sass/layout/_about.scss
> +  padding-bottom: 47px;
Може краще margin?

2021-03-12 20:34 UTC, Koliadjun commented on src/sass/layout/_about.scss
> +.about__description {
http://joxi.ru/zANgvN4sjqxJkr

2021-03-12 20:34 UTC, Koliadjun commented on src/sass/layout/_about.scss
> +  line-height: 1.58;
http://joxi.ru/gmv4KdOi1gBxLA

2021-03-12 20:34 UTC, Koliadjun commented on src/sass/layout/_about.scss
> +  padding-bottom: 47px;
http://joxi.ru/Vm6PVMzCvn0x1A

2021-03-12 20:34 UTC, Koliadjun commented on src/partials/about.html
> +                    <button type="button" class="btn-light">Read more</button>
http://joxi.ru/Q2KNvy4Tv8X9Rm
Потрібно поправити компоненту, щоб вона одинаково працювала, як для тегу <a> та і для <button>
Створити завдання на доопрацювання або сама підкоректуй

2021-03-12 20:34 UTC, Koliadjun commented on src/sass/components/_section_subtitle.scss
> +  @media screen and(min-width: 786px) {
768px

2021-03-12 20:34 UTC, Koliadjun commented on src/partials/about.html
> +                    <picture>
Якщо в нас картинки ідентичні на всіх пристроях то min-width як на мене лишній. Тут треба з командою подумати

2021-03-12 20:34 UTC, Koliadjun commented on src/sass/layout/_about.scss
> +    line-height: 1.79;
http://joxi.ru/YmExvOYCMX9wLr

2021-03-12 20:34 UTC, Koliadjun commented on src/sass/layout/_about.scss
> +  @media screen and (min-width: 768px) {
http://joxi.ru/Y2LJv74CENe7Pr

2021-03-12 20:34 UTC, Koliadjun commented on src/sass/layout/_about.scss
> +.img-thumb {
на планшеті картинка займає половину контеінеру. тому і текст не достає до краю контейнеру http://joxi.ru/ZrJlv14tn7eM92
http://joxi.ru/krDXw34t4nLJXr

2021-03-12 20:34 UTC, Koliadjun commented on src/partials/about.html
> +                    <picture>
http://joxi.ru/KAx4aKXiKoqKwA якась мала на десктопі

2021-03-12 20:34 UTC, Koliadjun commented on src/partials/about.html
> +                            media="(min-width: 786px)" type="image/webp" />
768px

2021-03-12 20:34 UTC, Koliadjun commented on src/partials/about.html
> +                            media="(min-width: 786px)" />
768px

2021-03-12 20:58 UTC, AngieBoiko commented on src/partials/about.html
> +            media="(min-width: 1200px)" type="image/webp" />
у нас по тз точка перелома для десктопа 1280px

2021-03-12 21:18 UTC, AngieBoiko commented on src/sass/layout/_about.scss
> +  width: 220px;
+, пусть тянется по контенту.Можно убрать дисплей блок, у р-шки он по умолчанию

2021-03-12 21:22 UTC, ikalyniak commented on src/partials/about.html
> +                    <picture>
что значит идентичные?

2021-03-12 21:23 UTC, ikalyniak commented on src/partials/about.html
> +                    <button type="button" class="btn-light">Read more</button>
свг должна лежать в кнопке. Я уже сделал, можешь забрать у меня в хедере

2021-03-12 21:27 UTC, ikalyniak commented on src/partials/about.html
> +                    <button type="button" class="btn-light">Read more</button>
.btn-light и .btn-dark - компоненты только для типовых значений, остальные отличаются и нужно прописывать, например паддинги-шмадинги и тд

background-color: хххх;
  border: 0;
  cursor: pointer;
  color: ххх;

2021-03-12 21:29 UTC, ikalyniak commented on src/sass/components/_section-subtitle.scss
> +  @media screen and(min-width: 786px) {
768 это болезнь)))

2021-03-12 21:29 UTC, ikalyniak commented on src/sass/components/_section-subtitle.scss
> +    line-height: 1.13;
1280

2021-03-12 21:31 UTC, AngieBoiko commented on src/partials/about.html
> +                    <picture>
они разного размера же

2021-03-12 21:46 UTC, ikalyniak commented on src/sass/layout/_about.scss
> +    background-position: left 0px top 200px;
на секцию max-width:1600 не вешай, а огрнаничивай фоновое ихображение, иначе секция прижимается  к левому краю а не центрируется на большом экран

2021-03-13 07:13 UTC, Koliadjun commented on src/partials/about.html
> +                    <picture>
> что значит идентичные?

Ну розмір в пікселях і відповідго співвідношення сторін. Це я мав на увазі

2021-03-13 07:15 UTC, Koliadjun commented on src/partials/about.html
> +                    <picture>
Все я додивився, що там різні картинки

2021-03-13 08:08 UTC, funnykoss commented on src/sass/layout/_about.scss
> +  width: 220px;
я пока не могу убрать width, потому как там текст должен на мобилке в две строки, дальше я убираю width

2021-03-13 08:24 UTC, funnykoss commented on src/sass/layout/_about.scss
> +    line-height: 1.79;
я на калькуляторе высчитала

2021-03-13 08:30 UTC, funnykoss commented on src/partials/about.html
> +        <p class="section_subtitle">tradition and love</p>
у меня макет поплыл,были разными титры,сейчас исправлю

2021-03-13 08:33 UTC, Koliadjun commented on src/sass/layout/_about.scss
> +    line-height: 1.79;
Ок і так може бути.

2021-03-13 09:34 UTC, funnykoss commented
ребят,спасибо за комменты,поплыл у меня макет(((и много недочетов,и,естественно,один раз неправильно написала 786 и все))поехало)все повносила,кроме кнопки,хочу ее доделать,когда  мердж ветки сделаю и солью то,что сделали ребята

2021-03-13 15:23 UTC, Koliadjun approved these changes
Хороша робота так тримати

2021-03-13 15:31 UTC, merged